### ISSUE TITLE
100% CPU on CentOS7

### ISSUE THREAD

**Issue by l3nz** [kz26/mailproxy#1]
I am running this on a CentOS 7 box with Python 3.5 and I see 100% CPU usage - though the relay works perfectly. DO you have any idea why?

**Comment by kz26** [comment]
Hmm, that's odd. I have a feeling it may be related more to aiosmtpd than mailproxy itself. Do you get 100% CPU usage as soon as mailproxy starts, or when sending an email?

**Comment by l3nz** [comment]
All of the time, since it starts. No difference when sending or not.

**Comment by kz26** [comment]
Ok, I'll see if I can reproduce and let you know what I find.

**Comment by l3nz** [comment]
Thanks.

**Comment by kz26** [comment]
Just pushed version 1.0.2 which should fix this. Thanks again for the report.

**Comment by l3nz** [comment]
Thanks - works like a charm.
